---
- name: Set the "home" variable
  ansible.builtin.set_fact:
    home: "{{ ansible_env.HOME }}"

- name: Rust | Check if ~/.cargo exists
  ansible.builtin.stat:
    path: "{{ home }}/.cargo"
  register: rust_cargo_dir

- name: Rust | Check if ~/.rustup exists
  ansible.builtin.stat:
    path: "{{ home }}/.rustup"
  register: rust_rustup_dir

- name: Rust | Check if the nightly toolchain is installed
  ansible.builtin.stat:
    path: "{{ home }}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu"
  register: rust_nightly_toolchain

- name: Rust | New installation
  when: not (rust_cargo_dir.stat.exists and rust_rustup_dir.stat.exists)
  block:
    - name: Rust | Download the Rust installation script
      ansible.builtin.get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: "755"
        force: true

    - name: Rust  | Run the Rust installation script
      ansible.builtin.command:
        cmd: /tmp/sh.rustup.rs -y --no-modify-path
      register: rust_installer_output
      changed_when: "'stable-x86_64-unknown-linux-gnu installed' in rust_installer_output.stdout"

- name: Rust | Existing installation
  ansible.builtin.command:
    cmd: ./rustup update stable
    chdir: "{{ home }}/.cargo/bin"
  changed_when: true
  when: rust_cargo_dir.stat.exists and rust_rustup_dir.stat.exists

- name: Rust | Install the nightly toolchain
  ansible.builtin.command:
    cmd: ./rustup toolchain install nightly
    chdir: "{{ home }}/.cargo/bin"
  changed_when: true
  when: not rust_nightly_toolchain.stat.exists

- name: Rust | Update the nightly toolchain
  ansible.builtin.command:
    cmd: ./rustup update nightly
    chdir: "{{ home }}/.cargo/bin"
  changed_when: true
  when: rust_nightly_toolchain.stat.exists

- name: Rust | Install rust-analyzer nightly
  ansible.builtin.command:
    cmd: ./rustup +nightly component add rust-analyzer-preview
    creates: "{{ home }}/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer"
    chdir: "{{ home }}/.cargo/bin"

- name: Rust | Configure cargo
  ansible.builtin.template:
    src: cargo_conf.toml.j2
    dest: "{{ home }}/.cargo/config.toml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0644"

- name: Rust | Ensure gcc is installed
  ansible.builtin.package:
    name: gcc
    state: present
  become: true

- name: Rust | Install packages with cargo
  community.general.cargo:
    name: "{{ item }}"
    state: present
  loop: "{{ cargo_packages }}"
  environment:
    PATH: "{{ home }}/.cargo/bin:{{ ansible_env.PATH }}"
  when: cargo_packages is defined
