---
- hosts:
    - arch
    - fedora

  vars_files:
    - "vars/{{ ansible_distribution }}.yml"
    - "defaults/main.yml"

  tasks:
    - name: Power management and system tweaks
      ansible.builtin.import_role:
        name: system
      tags: never, system

    - import_tasks: tasks/install-packages.yml
      tags: never, packages

    - import_tasks: tasks/flatpak.yml
      tags: never, flatpak

    - name: Install fonts
      ansible.builtin.import_role:
        name: fonts
      tags: never, fonts

    - name: Setup my dotfiles
      ansible.builtin.import_role:
        name: dotfiles
      tags: never, dotfiles

    - name: Setup podman
      ansible.builtin.import_role:
        name: podman
      tags: never, podman

    - name: Setup distrobox
      ansible.builtin.import_role:
        name: distrobox
      tags: never, distrobox

    - name: Install VirtualBox
      ansible.builtin.import_role:
        name: virtualbox
      tags: never, vbox

    - name: Install libvirt
      ansible.builtin.import_role:
        name: ansible-role-libvirt
      vars:
        libvirt_users_in_libvirt_group:
          - "{{ ansible_env.USER }}"
      tags: never, libvirt
      become: true

    - name: Setup vagrant
      ansible.builtin.import_role:
        name: vagrant
      tags: never, vagrant

    - name: Security
      ansible.builtin.import_role:
        name: ansible-role-security
      tags: never, security
      become: true

    - name: GNOME setup
      ansible.builtin.import_role:
        name: gnome
      tags: never, gnome

    - name: Rust
      ansible.builtin.import_role:
        name: rust
      tags: never, rust
