---
- hosts: all
  # connection: local

  vars:

  vars_files:
    - "vars/default-config.yml"
    - "vars/{{ ansible_distribution }}.yml"

  tasks:
    - name: Tasks that require sudo.
      block:
        - name: Pre-setup.
          include_tasks: "tasks/preparation-{{ ansible_distribution }}.yml"

        - name: Install must-have software.
          include_tasks: "tasks/install-packages.yml"
      become: true
