---
- hosts: all
  # connection: local

  vars:

  vars_files:
    - "vars/default-config.yml"
    - "vars/{{ ansible_distribution }}.yml"

  tasks:
    - name: Tasks that require sudo.
      block:
        - name: Pre-setup.
          include_tasks: "tasks/preparation-{{ ansible_distribution }}.yml"

        - name: Install must-have software.
          include_tasks: "tasks/install-packages.yml"

        # package_facts does NOT work for pacman (Archlinux)
        - name: Find installed packages (Fedora)
          package_facts:
            manager: auto
          when: ansible_distribution == "Fedora"

        - name: Find installed packages (Archlinux)
          command: pacman -Qn
          register: arch_installed_packages
          no_log: true
          failed_when: false
          changed_when: false
          when: ansible_distribution == "Archlinux"

        - name: Set fact about installed packages in Archlinux.
          set_fact:
            installed_packages: "{{ arch_installed_packages.stdout }}"
          when: ansible_distribution == "Archlinux"

        - name: Set fact about installed packages in Fedora
          set_fact:
            installed_packages: "{{ ansible_facts.packages }}"
          when: ansible_distribution == "Fedora"

        - name: Set capabilities.
          include_tasks: tasks/capabilities.yml
          when: configure_capabilities | bool

        - name: Sysctl tweaks.
          include_role:
            name: chzerv.sysctl
          vars:
            sysctl_required_packages: procps-ng
            sysctl_entries:
              - name: vm.swappiness
                value: 10
              - name: vm.dirty_ratio
                value: 6
              - name: vm.dirty_background_bytes
                value: 4194304
              - name: vm.vfs_cache_pressure
                value: 50
              - name: kernel.sysrq
                value: 1
          when: configure_sysctl | bool

        - name: Performance tuning.
          include_tasks: tasks/performance.yml
          when: configure_performance | bool
      become: true
