---
- hosts: all
  # connection: local

  vars:

  vars_files:
    - "vars/default-config.yml"

  tasks:
    - name: Tasks that require sudo.
      block:
        - name: Pre-setup.
          include_tasks: "tasks/preparation-{{ ansible_distribution }}.yml"
      become: true
