---
- hosts:
    - arch
    - fedora

  vars_files:
    - "vars/{{ ansible_distribution }}.yml"
    - "defaults/main.yml"

  tasks:
    - import_tasks: tasks/pre-setup.yml
      tags: always

    - import_tasks: "tasks/gather-facts.yml"
      tags: always

    - import_tasks: "tasks/Fedora-setup.yml"
      when: ansible_distribution == "Fedora"
      tags: setup

    - import_tasks: "tasks/Arch-setup.yml"
      when: ansible_distribution == "Archlinux"
      tags: setup

    - import_tasks: tasks/install-packages.yml
      tags: never,packages

    - import_tasks: tasks/flatpak.yml
      tags: never,flatpak

    - import_tasks: "tasks/gather-facts.yml"
      tags: ["always"]

    - import_tasks: "tasks/fonts.yml"
      tags: never,fonts

    - import_tasks: "tasks/virtualization-containers.yml"
      tags: never,virt
      become: true

    - import_tasks: "tasks/gnome-setup.yml"
      tags: never,gnome
      when: "'gnome-shell' in installed_packages"

    - import_tasks: "tasks/powersaving.yml"
      tags: never,powersaving
      become: true

    - name: Setup my dotfiles
      ansible.builtin.import_role:
        name: dotfiles
      tags: never,dotfiles
