---
- hosts:
    - arch
    - fedora

  vars_files:
    - "vars/{{ ansible_distribution }}.yml"
    - "defaults/main.yml"

  tasks:
    - name: Base
      ansible.builtin.import_role:
        name: base
      tags: never, base

    - name: Install VirtualBox
      ansible.builtin.import_role:
        name: virtualbox
      tags: never, vbox

    - name: Install libvirt
      ansible.builtin.import_role:
        name: ansible-role-libvirt
      vars:
        libvirt_users_in_libvirt_group:
          - "{{ ansible_env.USER }}"
      tags: never, libvirt
      become: true

    - name: Setup vagrant
      ansible.builtin.import_role:
        name: vagrant
      tags: never, vagrant

    - name: Security
      ansible.builtin.import_role:
        name: ansible-role-security
      tags: never, security
      become: true

    - name: GNOME setup
      ansible.builtin.import_role:
        name: gnome
      tags: never, gnome

    - name: Rust
      ansible.builtin.import_role:
        name: rust
      tags: never, rust
