---
- name: Enable additional repositories for Fedora
  block:
    - name: Enable RPM Fusion
      ansible.builtin.dnf:
        name: "https://mirrors.rpmfusion.org/{{ item }}/fedora/rpmfusion-{{ item }}-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      loop:
        - free
        - nonfree

    - name: Enable COPR repositories
      community.general.copr:
        name: "{{ item }}"
        state: enabled
      loop:
        - atim/lazygit
        - atim/bottom

    - name: Enable Tailscale's repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        creates: /etc/yum.repos.d/tailscale.repo
      changed_when: true

    - name: Enable Hashicorp's repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo
        creates: /etc/yum.repos.d/hashicorp.repo
      changed_when: true

  become: true
  when: ansible_distribution == "Fedora"
