---
- name: Ensure the $HOME/AUR directory exists
  ansible.builtin.file:
    path: "{{ home }}/AUR"
    state: directory
    mode: "0755"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Ensure base-devel, git and ccache are installed
  community.general.pacman:
    name:
      - base-devel
      - git
      - ccache
    state: present
  become: true

- name: Clone AUR package(s)
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ item }}"
    dest: "{{ home }}/AUR/{{ item }}"
    force: true
  loop: "{{ aur_packages | flatten(levels=1) }}"

- name: Build AUR package(s)
  ansible.builtin.command:
    cmd: "makepkg -sirc --noconfirm"
    chdir: "{{ home }}/AUR/{{ item }}"
  changed_when: true
  loop: "{{ aur_packages | flatten(levels=1) }}"
