---
- name: Ensure the ~/.local/share/applications directory exists.
  file:
    path: "{{ ansible_user_dir }}/.local/share/applications"
    state: directory
    mode: "0644"

- name: Ensure the ~/.local/share/mime/packages directory exists.
  file:
    path: "{{ ansible_user_dir }}/.local/share/mime/packages"
    state: directory
    mode: "0644"

- name: Ensure the ~/.config directory exists.
  file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: Ensure the ~/.config/systemd/user directory exists.
  file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory
    mode: "0755"
