---
- name: Manage flatpak repositories.
  flatpak_remote:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    flatpakrepo_url: "{{ item.flatpakrepo_url }}"
    method: "{{ item.method | default('system') }}"
  with_items: "{{ flatpak_repositories }}"

- name: Install packages from flatpak.
  flatpak:
    name: "{{ item.name | default(item) }}"
    remote: "{{ item.remote | default('flathub') }}"
    method: "{{ item.method | default('system') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ flatpak_packages }}"

- name: Install packages with pip.
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default('~/.venvs') }}"
  with_items: "{{ pip_packages }}"

- name: Install packages with npm, globally.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ npm_packages }}"
  environment:
    npm_config_prefix: "{{ npm_installation_path }}"
