---
- name: Install core packages.
  package:
    name: "{{ core_software }}"
    state: present

- name: Install utility software.
  package:
    name: "{{ utility_software }}"
    state: present

- name: Install monitoring software.
  package:
    name: "{{ monitoring_software }}"
    state: present

- name: Install Ansible packages.
  package:
    name: "{{ ansible_packages }}"
    state: present

- name: Install software for writing.
  package:
    name: "{{ writing_software }}"
    state: present

- name: Install fonts.
  package:
    name: "{{ font_packages }}"
    state: present
  become: true

- name: Install packages from RPMFusion (Fedora).
  package:
    name: "{{ rpmfusion_software }}"
    state: present
  when:
    - ansible_distribution == "Fedora"
    - fedora_enable_rpmfusion_non_free | bool or fedora_enable_rpmfusion_free | bool

- name: Install packages for managing BTRFS snapshots, if BTRFS is used.
  package:
    name: "{{ btrfs_packages }}"
    state: present
  when: "root_fs_type == ['btrfs']"
