---
- name: Ensure ~/.gnupg directory exists.
  file:
    path: "{{ ansible_user_dir }}/.gnupg"
    state: directory
    mode: "0700"
    owner: "{{ ansible_user_id }}"

- name: Configure gpg agent.
  lineinfile:
    path: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    create: true
    backup: true
    mode: "0644"
    owner: root
    group: root
  with_items:
    - regexp: "^max-cache-ttl"
      line: "max-cache-ttl {{ gpg_agent_max_cache_ttl }}"
    - regexp: "^default-cache-ttl"
      line: "default-cache-ttl {{ gpg_agent_default_cache_ttl }}"
    - regexp: "^pinentry-program*"
      line: "pinentry-program /usr/bin/pinentry-gnome3"
  become: true

- name: Configure Ansible.
  block:
    - name: Change where Ansible roles are saved.
      lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: "^#roles_path"
        line: "roles_path = {{ ansible_roles_path }}"
        mode: "0644"
        owner: root
        group: root

    - name: Change Ansible's remote_tmp path.
      lineinfile:
        path: /etc/ansible/ansible.cfg
        regexp: "^#remote_tmp"
        line: "remote_tmp = /tmp"
        mode: "0644"
        owner: root
        group: root
  become: true
  when: "'ansible' in installed_packages"

- name: Add additional kernel parameters (GRUB).
  template:
    src: etc/default/grub.j2
    dest: /etc/default/grub
    backup: true
    mode: "0644"
    owner: root
    group: root
  become: true
  when:
    - grub_is_installed.stat.exists | bool

- name: Add additional kernel parameters (Archlinux, systemd-boot).
  template:
    src: boot/loader/entries/arch.conf.j2
    dest: /boot/loader/entries/arch.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
  become: true
  when:
    - not grub_is_installed.stat.exists | bool
    - ansible_distribution == "Archlinux"

- name: Ensure dbus-broker is enabled on boot.
  systemd:
    name: dbus-broker
    enabled: true
    scope: global
  become: true

- name: Enable WOL on the network adapter.
  template:
    src: etc/systemd/network/50-wired.link.j2
    dest: /etc/systemd/network/50-wired.link
    mode: "0644"
    owner: root
    group: root
  become: true
