---
- name: Change I/O scheduler depending on disk type (NVMe v SSD v HDD).
  template:
    src: 60-ioschedulers.rules.j2
    dest: /etc/udev/rules.d/60-ioschedulers.rules
    mode: "0644"
    owner: root
    group: root

- name: Setup earlyoom.
  block:
    - name: Configure earlyoom
      template:
        src: etc/default/earlyoom.j2
        dest: /etc/default/earlyoom
        mode: "0644"
        owner: root
        group: root

    - name: Ensure earlyoom service is started and enabled at boot.
      service:
        name: earlyoom
        state: started
        enabled: true
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version | int <= 33

- name: Configure systemd-oomd
  block:
    - name: Configure systemd-oom.
      template:
        src: etc/systemd/oomd.conf.j2
        dest: /etc/systemd/oomd.conf
        mode: "0644"
        owner: root
        group: root

    - name: Ensure systemd-oomd service is started and enabled at boot.
      service:
        name: systemd-oomd
        state: started
        enabled: true
  when: (ansible_distribution == "Fedora" and ansible_distribution_major_version | int > 33) or (ansible_distribution == "Archlinux")

- name: Find hardware watchdog kernel modules.
  shell:
    cmd: wdctl | grep -i identity | awk '{ print $2 }'
  register: hw_watchdog_module
  failed_when: false
  changed_when: false
  no_log: true

- name: Blacklist hardware watchdog kernel module.
  kernel_blacklist:
    name: "{{ hw_watchdog_module.stdout }}"
    state: present
  when: hw_watchdog_module is defined
