---
- name: Configure dnf (Fedora).
  template:
    src: etc/dnf/dnf.conf.j2
    dest: /etc/dnf/dnf.conf
    mode: "0644"
    owner: root
    group: root
    backup: true

- name: Ensure system is up-to-date (Fedora).
  dnf:
    update_cache: true
    name: "*"
    state: latest

- name: Enable RPM Fusion Free (Fedora).
  dnf:
    name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: fedora_enable_rpmfusion_free | bool

- name: Enable RPM Fusion Non-Free (Fedora).
  dnf:
    name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: fedora_enable_rpmfusion_non_free | bool

# The dnf module doesn't support these functions, so the shell module
# is used.
- name: Setup RPM Fusion (Fedora).
  shell: >
    dnf groupupdate core -y &&
    dnf groupupdate multimedia --setop="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y &&
    dnf groupupdate sound-and-video -y
  args:
    warn: false
  changed_when: true
  when: fedora_enable_rpmfusion_non_free | bool or fedora_enable_rpmfusion_free | bool

- name: Update system once again (Fedora).
  dnf:
    update_cache: true
    name: "*"
    state: latest
