---
- name: Enable mulitlib repository for pacman (Archlinux).
  blockinfile:
    path: /etc/pacman.conf
    insertafter: '^#\[multilib\]'
    backup: true
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
  when: arch_enable_multilib | bool

- name: Improve pacman's output (ArchLinux).
  lineinfile:
    dest: /etc/pacman.conf
    regexp: "^{{ item.regexp }}"
    insertafter: "{{ item.insertafter | default(omit) }}"
    line: "{{ item.line }}"
    state: present
    backup: true
  with_items:
    - regexp: '^\#UseSyslog'
      line: "UseSyslog"
    - regexp: '^\#Color'
      line: "Color"
    - regexp: '^\#TotalDownload'
      line: "TotalDownload"
    - regexp: "^#VerbosePkgLists"
      line: "VerbosePkgLists"
    - regexp: "^ILoveCandy"
      insertafter: "^VerbosePkgLists"
      line: "ILoveCandy"

- name: Ensure system is up-to-date (ArchLinux)
  pacman:
    update_cache: true
    upgrade: true

- name: Update pacman mirrorlist (Archlinux)
  block:
    - name: Install reflector to update pacman mirrorlist (Archlinux)
      pacman:
        name: reflector
        state: present

    - name: Update pacman mirrorlist (Archlinux).
      shell: >-
        reflector --country Greece --latest 50 --sort rate --age 48
        --save /etc/pacman.d/mirrorlist
