---
- name: Configure pacman (Archlinux).
  template:
    src: etc/pacman.conf.j2
    dest: /etc/pacman.conf
    mode: "0644"
    owner: root
    group: root
    backup: true

- name: Ensure system is up-to-date (ArchLinux)
  pacman:
    update_cache: true
    upgrade: true
