---
- name: tmux setup | Ensure tmux is installed
  ansible.builtin.package:
    name: tmux
    state: present
  become: true

- name: tmux setup | Symlink tmux to ~/.config
  ansible.builtin.file:
    src: "{{ dotfiles_dest }}/config/tmux"
    dest: "{{ home }}/.config/tmux"
    state: link
    mode: "0755"

- name: tmux setup | Clone tpm plugin manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm"
    version: master
    force: true
