---
default_user: "{{ ansible_user_id }}"

arch_enable_multilib: true
fedora_enable_rpmfusion_free: true
fedora_enable_rpmfusion_non_free: true

configure_capabilities: true
configure_sysctl: true
configure_performance: true
configure_gnome: true
configure_systemd: true
configure_dotfiles: true

flatpak_packages: []
# flatpak_packages:
#   - name: com.discordapp.Discord
#     remote: flathub # defaults to flathub
#     method: user # user/system, default: user
#     state: present # present/absent/latest, default: present

pip_packages: []
# pip_packages:
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
#   virtualenv:  ~/.venvs # default: N/A

npm_packages: []
# npm_packages:
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A

mutter_enable_experimental: false

dotfiles_repo: git@github.com:chzerv/dotfiles.git
dotfiles_local_destination: "{{ ansible_user_dir }}/dotfiles"
dotfiles_accept_hostkey: true

dotfiles_config_choices:
  - alacritty
  - bat
  - nvim
  - tilix
  - tmux
  - zsh
  - doom
