- name: Doom Emacs setup.
  block:
    - name: Install emacs
      package:
        name: emacs
        state: present
      become: true

    - name: Clone Doom Emacs.
      git:
        repo: "https://github.com/hlissner/doom-emacs.git"
        dest: "{{ ansible_user_dir }}/.emacs.d"
        depth: 1
        version: master
