---
- name: Install emacs
  package:
    name: emacs
    state: present
  become: true

- name: Ensure ~/.emacs.d exists.
  stat:
    path: "{{ ansible_user_dir }}/.emacs.d"
  register: emacs_dir_exists

- name: Clone Doom Emacs.
  git:
    repo: "https://github.com/hlissner/doom-emacs.git"
    dest: "{{ ansible_user_dir }}/.emacs.d"
    version: develop
    depth: 1
  when: not emacs_dir_exists.stat.exists

- name: Install Doom Emacs.
  command:
    cmd: "{{ ansible_user_dir }}/.emacs.d/bin/doom -y install"
  changed_when: true

- name: Ensure a desktop file for emacsclient is present.
  template:
    src: local/share/applications/emacs-client.desktop.j2
    dest: "{{ ansible_user_dir }}/.local/share/applications/emacs-client.desktop"
    mode: "0644"

- name: Ensure a mime type for Org-mode is present.
  template:
    src: local/share/mime/packages/org.xml.j2
    dest: "{{ ansible_user_dir }}/.local/share/mime/packages/org.xml"
    owner: "{{ ansible_user_id }}"
    mode: "0644"

- name: Ensure the mime database is up-to-date.
  command:
    cmd: update-mime-database ~/.local/share/mime
  changed_when: true

- name: Ensure emacs is the default handler for the text/org mime type.
  command:
    cmd: xdg-mime default emacs.desktop text/org
  changed_when: true

# TODO: Automatically create a firefox bookmarklet.
- name: Ensure a mime type for Org-protocol is present.
  template:
    src: local/share/mime/packages/org-protocol.desktop.j2
    dest: "{{ ansible_user_dir }}/.local/share/mime/packages/org.xml"
    owner: "{{ ansible_user_id }}"
    mode: "0644"

- name: Associate org-protocol links with the desktop file.
  command:
    cmd: xdg-mime default org-protocol.desktop x-scheme-handler/org-protocol
  changed_when: true

- name: Ensure dependencies of enabled modules are installed.
  package:
    name: "{{ emacs_packages }}"
    state: present
  become: true
