- name: Install emacs
  package:
    name: emacs
    state: present
  become: true

- name: Ensure ~/.emacs.d exists.
  stat:
    path: "{{ ansible_user_dir }}/.emacs.d"
  register: emacs_dir_exists

- name: Clone Doom Emacs.
  git:
    repo: "https://github.com/hlissner/doom-emacs.git"
    dest: "{{ ansible_user_dir }}/.emacs.d"
    version: master
  when: not emacs_dir_exists.stat.exists
