---
- name: tilix | Ensure dconf is installed
  package:
    name: dconf
    state: present
  become: true

- name: tilix | Ensure tilix is installed
  package:
    name: dconf
    state: present
  become: true

- name: Load configuration into tilix.
  shell: "dconf load /com/gexperts/Tilix/ < {{ ansible_user_dir }}/.config/tilix/tilix.conf"
