---
- name: Ensure `unzip` is installed
  ansible.builtin.package:
    name: unzip
    state: present
  become: true

- name: Ensure the ~/.local/share/fonts directory exists
  ansible.builtin.file:
    path: "{{ home }}/.local/share/fonts"
    state: directory
    mode: "0755"

- name: Download Nerd Fonts
  include_tasks: download-fonts.yml
  loop:
    - Hasklig
    - JetBrainsMono
    - FiraCode
    - VictorMono

- name: Install other fonts
  ansible.builtin.package:
    name: "{{ font_packages }}"
    state: present
  become: true
